name: .NET

on:
  push:
    branches: [ main, dev, dev/*, feature/*, fix/*, release/* ]

  pull_request:
    branches: [ main ]

  release:
    types: [ published ]
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: false

    # Create Local NuGet Source

    - name: Create Local NuGet Directory
      run: mkdir ~/nuget

    - name: Add Local Nuget Source
      run: dotnet nuget add source ~/nuget

    # Func.Abstractions.Async

    - name: Restore Func.Abstractions.Async
      run: dotnet restore ./src/*/*/Func.Abstractions.Async.csproj

    - name: Build Func.Abstractions.Async
      run: dotnet build ./src/*/*/Func.Abstractions.Async.csproj --no-restore  -c Release

    - name: Pack Func.Abstractions.Async
      run: dotnet pack ./src/*/*/Func.Abstractions.Async.csproj --no-restore -o ~/nuget  -c Release

    # Func.Abstractions.AsyncValue

    - name: Restore Func.Abstractions.AsyncValue
      run: dotnet restore ./src/*/*/Func.Abstractions.AsyncValue.csproj

    - name: Build Func.Abstractions.AsyncValue
      run: dotnet build ./src/*/*/Func.Abstractions.AsyncValue.csproj --no-restore  -c Release

    - name: Pack Func.Abstractions.AsyncValue
      run: dotnet pack ./src/*/*/Func.Abstractions.AsyncValue.csproj --no-restore -o ~/nuget  -c Release

    # Func.Abstractions.Sync

    - name: Restore Func.Abstractions.Sync
      run: dotnet restore ./src/*/*/Func.Abstractions.Sync.csproj

    - name: Build Func.Abstractions.Sync
      run: dotnet build ./src/*/*/Func.Abstractions.Sync.csproj --no-restore  -c Release

    - name: Pack Func.Abstractions.Sync
      run: dotnet pack ./src/*/*/Func.Abstractions.Sync.csproj --no-restore -o ~/nuget  -c Release

    # Func.Abstractions

    - name: Restore Func.Abstractions
      run: dotnet restore ./src/*/*/Func.Abstractions.csproj

    - name: Build Func.Abstractions
      run: dotnet build ./src/*/*/Func.Abstractions.csproj --no-restore  -c Release

    - name: Pack Func.Abstractions
      run: dotnet pack ./src/*/*/Func.Abstractions.csproj --no-restore -o ~/nuget  -c Release

    # Func.Extensions.Async

    - name: Restore Func.Extensions.Async
      run: dotnet restore ./src/*/*/Func.Extensions.Async.csproj

    - name: Build Func.Extensions.Async
      run: dotnet build ./src/*/*/Func.Extensions.Async.csproj --no-restore  -c Release

    - name: Pack Func.Extensions.Async
      run: dotnet pack ./src/*/*/Func.Extensions.Async.csproj --no-restore -o ~/nuget  -c Release

    - name: Restore Func.Extensions.Async.Tests.Primary
      run: dotnet restore ./src/*/*/Func.Extensions.Async.Tests.Primary.csproj

    - name: Test Func.Extensions.Async.Tests.Primary
      run: dotnet test ./src/*/*/Func.Extensions.Async.Tests.Primary.csproj --no-restore  -c Release

    - name: Restore Func.Extensions.Async.Tests.DefCancellation
      run: dotnet restore ./src/*/*/Func.Extensions.Async.Tests.DefCancellation.csproj

    - name: Test Func.Extensions.Async.Tests.DefCancellation
      run: dotnet test ./src/*/*/Func.Extensions.Async.Tests.DefCancellation.csproj --no-restore  -c Release

    # Func.Extensions.AsyncValue

    - name: Restore Func.Extensions.AsyncValue
      run: dotnet restore ./src/*/*/Func.Extensions.AsyncValue.csproj

    - name: Build Func.Extensions.AsyncValue
      run: dotnet build ./src/*/*/Func.Extensions.AsyncValue.csproj --no-restore  -c Release

    - name: Pack Func.Extensions.AsyncValue
      run: dotnet pack ./src/*/*/Func.Extensions.AsyncValue.csproj --no-restore -o ~/nuget  -c Release

    - name: Restore Func.Extensions.AsyncValue.Tests.Primary
      run: dotnet restore ./src/*/*/Func.Extensions.AsyncValue.Tests.Primary.csproj

    - name: Test Func.Extensions.AsyncValue.Tests.Primary
      run: dotnet test ./src/*/*/Func.Extensions.AsyncValue.Tests.Primary.csproj --no-restore  -c Release

    - name: Restore Func.Extensions.AsyncValue.Tests.DefCancellation
      run: dotnet restore ./src/*/*/Func.Extensions.AsyncValue.Tests.DefCancellation.csproj

    - name: Test Func.Extensions.AsyncValue.Tests.DefCancellation
      run: dotnet test ./src/*/*/Func.Extensions.AsyncValue.Tests.DefCancellation.csproj --no-restore  -c Release

    # Func.Extensions.Sync

    - name: Restore Func.Extensions.Sync
      run: dotnet restore ./src/*/*/Func.Extensions.Sync.csproj

    - name: Build Func.Extensions.Sync
      run: dotnet build ./src/*/*/Func.Extensions.Sync.csproj --no-restore  -c Release

    - name: Pack Func.Extensions.Sync
      run: dotnet pack ./src/*/*/Func.Extensions.Sync.csproj --no-restore -o ~/nuget  -c Release

    - name: Restore Func.Extensions.Sync.Tests
      run: dotnet restore ./src/*/*/Func.Extensions.Sync.Tests.csproj

    - name: Test Func.Extensions.Sync.Tests
      run: dotnet test ./src/*/*/Func.Extensions.Sync.Tests.csproj --no-restore  -c Release

    # Func.Extensions

    - name: Restore Func.Extensions
      run: dotnet restore ./src/*/*/Func.Extensions.csproj

    - name: Build Func.Extensions
      run: dotnet build ./src/*/*/Func.Extensions.csproj --no-restore  -c Release

    - name: Pack Func.Extensions
      run: dotnet pack ./src/*/*/Func.Extensions.csproj --no-restore -o ~/nuget  -c Release

      # Push

    - name: Push Packages
      if: ${{ github.event_name == 'release' }}
      run: dotnet nuget push "../../../nuget/*.nupkg" -s https://api.nuget.org/v3/index.json -k ${{ secrets.NuGetSourcePassword }} --skip-duplicate
